[package]
name = "jaka_roplat_multilang"
version = "0.1.0"
edition = "2024"
build = "build.rs"
publish = false

[dependencies]
libjaka = { path = "../../libjaka-rs" }
robot_behavior = { path = "../../robot_behavior" }
roplat = { path = "../../../roplat/roplat" }
roplat_py = { path = "../../../roplat/roplat_py" }
rsbullet = { path = "../../rsbullet/rsbullet" }
tokio = { version = "1.47", features = ["rt-multi-thread", "macros", "time"] }

[build-dependencies]
roplat_build = "0.2.1"
