# Auto-generated by roplat_msg - DO NOT EDIT
import ctypes
from typing import Optional


class CurveBatch(ctypes.Structure):
    _fields_ = [
        ("seq", ctypes.c_uint64),
        ("point_x", ctypes.c_double * 8),
        ("point_y", ctypes.c_double * 8),
        ("point_z", ctypes.c_double * 8),
        ("target_joint", ctypes.c_double * 6),
        ("done", ctypes.c_uint8),
    ]

    def __repr__(self) -> str:
        fields = ', '.join(f'{name}={getattr(self, name)}' for name, _ in self._fields_)
        return f'CurveBatch({fields})'
