# Auto-generated by roplat_msg - DO NOT EDIT
import ctypes
from typing import Optional


class MotionTick(ctypes.Structure):
    _fields_ = [
        ("seq", ctypes.c_uint64),
        ("time_s", ctypes.c_double),
        ("dt_s", ctypes.c_double),
        ("current_joint", ctypes.c_double * 6),
        ("done", ctypes.c_uint8),
    ]

    def __repr__(self) -> str:
        fields = ', '.join(f'{name}={getattr(self, name)}' for name, _ in self._fields_)
        return f'MotionTick({fields})'
