# Auto-generated by roplat - DO NOT EDIT
from abc import ABC, abstractmethod


class Node(ABC):
    """Base class for all roplat nodes (Python side).

    Mirrors the Rust `roplat::Node` trait and C++ `roplat::Node<In, Out>` template.
    Subclasses should override `process` with a typed signature.
    """

    def on_init(self) -> None:
        """Called before the first process() invocation."""
        pass

    def on_shutdown(self) -> None:
        """Called after the last process() invocation."""
        pass

    @abstractmethod
    def process(self, *args, **kwargs):
        """Core processing logic. Subclasses must override with typed signature."""
        raise NotImplementedError
