// Auto-generated by roplat — DO NOT EDIT
#include "../src/cpp_spatial_curve.h"

extern "C" {

void* roplat_node_cpp_spatial_curve_create() {
    return new CppSpatialCurve();
}

void roplat_node_cpp_spatial_curve_destroy(void* ptr) {
    delete static_cast<CppSpatialCurve*>(ptr);
}

int roplat_node_cpp_spatial_curve_init(void* ptr) {
    static_cast<CppSpatialCurve*>(ptr)->on_init();
    return 0;
}

int roplat_node_cpp_spatial_curve_shutdown(void* ptr) {
    static_cast<CppSpatialCurve*>(ptr)->on_shutdown();
    return 0;
}

CurveBatch roplat_node_cpp_spatial_curve_process(void* ptr, const TrajectoryPlan* input) {
    return static_cast<CppSpatialCurve*>(ptr)->process(*input);
}

void roplat_node_cpp_spatial_curve_set_fields(void* ptr, double radius_m, double height_m, double turns) {
    auto* n = static_cast<CppSpatialCurve*>(ptr);
    n->setRadius_m(radius_m);
    n->setHeight_m(height_m);
    n->setTurns(turns);
}

} // extern "C"
